title: VCSLab
email: cskh_anm@viettel.com.vn
description: >- # this means to ignore newlines until "baseurl:"
  On this website, we publish our research results in the Viettel Vulnerabilities Disclosure program including vulnerabilities, badges, publications.
baseurl: "/"
url: "https://lab.viettelcybersecurity.com/"
twitter_username: vcslab
github_username:  vcslab
google_analytics: "G-C1YDQJJ0R8"
plugins:
 - jekyll-feed
 - jekyll-seo-tag